/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Bayu Purnama Aji
 */
public class role extends javax.swing.JFrame {

    /**
     * Creates new form role
     */
    public role() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleAdmin = new javax.swing.JButton();
        roleDosen = new javax.swing.JButton();
        roleMahasiswa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roleAdmin.setBackground(new java.awt.Color(84, 164, 189));
        roleAdmin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roleAdmin.setText("ADMIN");
        roleAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleAdminActionPerformed(evt);
            }
        });
        getContentPane().add(roleAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 200, 80));

        roleDosen.setBackground(new java.awt.Color(84, 164, 189));
        roleDosen.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        roleDosen.setText("DOSEN");
        roleDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleDosenActionPerformed(evt);
            }
        });
        getContentPane().add(roleDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 190, 80));

        roleMahasiswa.setBackground(new java.awt.Color(84, 164, 189));
        roleMahasiswa.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        roleMahasiswa.setText("MAHASISWA");
        roleMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleMahasiswaActionPerformed(evt);
            }
        });
        getContentPane().add(roleMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 277, 200, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/component_ui/Login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roleDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleDosenActionPerformed
        JOptionPane.showMessageDialog(null, "Anda telah masuk ke role Dosen");
    }//GEN-LAST:event_roleDosenActionPerformed

    private void roleAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleAdminActionPerformed
        JOptionPane.showMessageDialog(null, "Anda telah masuk ke role Admin");
    }//GEN-LAST:event_roleAdminActionPerformed

    private void roleMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleMahasiswaActionPerformed
    JOptionPane.showMessageDialog(null, "Anda telah masuk ke role Mahasiswa");
    }//GEN-LAST:event_roleMahasiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(role.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new role().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton roleAdmin;
    private javax.swing.JButton roleDosen;
    private javax.swing.JButton roleMahasiswa;
    // End of variables declaration//GEN-END:variables
}
